### ISSUE TITLE
coordinate first pass at ESM support for all instrumentations

### ISSUE THREAD

**Issue by trentm** [open-telemetry/opentelemetry-js-contrib#1942]
This is a meta issue to coordinate doing a first pass at ECMAScript module (ESM) support and a test for every node.js instrumentation. (This is about working with the `import-in-the-middle`-based hook so is not relevant to browser instrumentations.)  I'm not necessarily volunteering to *do* all these :), but I'll certainly help.

Hopefully this can also be useful for support/help requests for why instrumentation might not be working for ESM-using code. If the module/instrumentation in question is not checked off here, then ESM instrumentation is not expected to work (it might be luck).

- [ ] instrumentation-grpc (core repo)
- [x] instrumentation-http (core repo, [support + test](https://github.com/open-telemetry/opentelemetry-js/pull/4866))
- [ ] instrumentation-amqplib
- [ ] instrumentation-cucumber
- [ ] instrumentation-dataloader ([support](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2813))
- [ ] instrumentation-fs
- [ ] instrumentation-lru-memoizer
- [x] instrumentation-mongoose (#2793)
- [ ] instrumentation-socket.io
- [ ] instrumentation-tedious
- [ ] instrumentation-aws-lambda (support: https://github.com/open-telemetry/opentelemetry-js/pull/5094 and https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2508, missing test)
- [ ] instrumentation-aws-sdk
- [ ] instrumentation-bunyan
- [ ] instrumentation-cassandra
- [ ] instrumentation-connect
- [ ] instrumentation-dns
- [x] instrumentation-express ([test](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1966))
- [ ] instrumentation-fastify ([test](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1763); there is an ESM limitation, see below)
- [ ] instrumentation-generic-pool
- [ ] instrumentation-graphql
- [x] instrumentation-hapi ([support + test](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2184))
- [x] instrumentation-ioredis ([support](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1694), [test](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1735))
- [ ] instrumentation-knex
- [x] instrumentation-koa ([support + test](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1736))
- [ ] instrumentation-memcached
- [ ] instrumentation-mongodb
- [ ] instrumentation-mysql
- [ ] instrumentation-mysql2
- [ ] instrumentation-nestjs-core
- [ ] instrumentation-net
- [x] instrumentation-pg ([support](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1701), [test](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/d9e757f585b346767406eabd4f491399dafc15b8/plugins/node/opentelemetry-instrumentation-pg/test/pg.test.ts#L1098-L1125), [pg-pool fix](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2807))
- [x] instrumentation-pino ([support](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1831), test was [accidentally partially removed](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1867), so need to restore that, [test re-added](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2176))
- [ ] instrumentation-redis
- [ ] instrumentation-redis-4
- [ ] instrumentation-restify
- [ ] instrumentation-router
- [ ] instrumentation-winston

# dev notes

Run the following to show which (contrib-repo) instrumentations have an ESM-related test.
This shows usage of the required experimental-loader hook to support hooking ESM modules.

```
rg hook.mjs -g '*.test.*'
```

# Guide on adding ESM support and an ESM test to an instrumentation

TODO(trentm)
- https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1735 added `runTestFixture`

**Comment by trentm** [comment]
# notes on fastify ESM support

Fastify ESM support is slightly limited. The current import style in "opentelemetry-js-contrib/plugins/node/opentelemetry-instrumentation-fastify/test/fixtures/use-fastify.mjs" works, but this fails:

```js
...
import * as mod from 'fastify';
console.log('mod: ', mod);
const app = mod.fastify();
...
```

Here `mod.default` is instrumented, but `mod.fastify` is not.
This is probably an exceedingly rare way to import and use fastify. Still,
this is why I haven't checked fastify above.

**Comment by tobiasmuehl** [comment]
According to [this post](https://github.com/open-telemetry/opentelemetry-js/issues/4437#issue-2097081865), the following already work, based likely on luck:
- `graphql`
- `@grpc/grpc-js`

**Comment by tobiasmuehl** [comment]
__🎉 I found a working solution here!__ My project is using esm and I switched my runtime from `node` to [`jiti`](https://github.com/unjs/jiti) and NOW EVERYTHING JUST WORKS!!!!!! I'm using http, express and pg instrumentations

If we are living in a simulation then this is a complete cheat code 🥷🏼

**Comment by trentm** [comment]
> Your checklist only supports binary display ...

Heh. I don't object to more info being included in each bullet point. I'd like to keep the checkboxes. To me "checked" will mean "we've done a first pass on ESM instrumentation for this module". When everything is checked, we can close this issue. There could be separate follow-up issues for particular limitations.

**Comment by rendmath** [comment]
We conducted tests for an ESM migration of a Node.js application auto-instrumented with OpenTelemetry.

So far we can confirm that we have spans for:
- `instrumentation-dns`
- `instrumentation-http`
- `instrumentation-express`

But the tests are currently failing for `instrumentation-net` (no spans).
