### ISSUE TITLE
[all] support ESM instrumentation for Node.js v18.19, v20, v21

### ISSUE THREAD

**Issue by pichlermarc** [open-telemetry/opentelemetry-js-contrib#2021]
Currently we use an older version of `import-in-the-middle` that does not work with 
- Node.js v18.19
- Node.js v20
- Node.js v21

We're blocked on updating to `import-in-the-middle@1.7.3` in the core repo as that version includes a bug (https://github.com/DataDog/import-in-the-middle/issues/57) which breaks our way of detecting ESM packages. We do this ESM detection in multiple packages. 

**To resolve this issue there are two options:**

- **Option 1 (preferred)**: contribute a fix for https://github.com/DataDog/import-in-the-middle/issues/57 upstream
  - [x] contribute a fix (thanks @trentm :tada: - https://github.com/DataDog/import-in-the-middle/pull/66)
  - [x] wait for the release of import-in-the-middle
- ~~**Option 2:** implement an ESM detection workaround in this repo, which does not rely on `@@toStringTag` in~~ (we're going for option 1) 
  - [ ] [`@opentelemetry/instrumentation-koa`](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/9df30ea0fd822a69203b818b8fbe34e1e1c8bced/plugins/node/opentelemetry-instrumentation-koa/src/instrumentation.ts#L60)
  - [ ] [`@opentelemetry/instrumentation-ioredis`](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/9df30ea0fd822a69203b818b8fbe34e1e1c8bced/plugins/node/opentelemetry-instrumentation-ioredis/src/instrumentation.ts#L54)
  - [ ] [`@opentelemetry/instrumentation-bunyan`](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/9df30ea0fd822a69203b818b8fbe34e1e1c8bced/plugins/node/opentelemetry-instrumentation-bunyan/src/instrumentation.ts#L55)
  - [ ] [`@opentelemetry/instrumentation-pg`](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/9df30ea0fd822a69203b818b8fbe34e1e1c8bced/plugins/node/opentelemetry-instrumentation-pg/src/instrumentation.ts#L71)
    - this is currently missing tests for ESM, so implementing a workaround would require implementing tests for it first, #1942  
  - [ ] [`@opentelemetry/instrumentation-pino`](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/9df30ea0fd822a69203b818b8fbe34e1e1c8bced/plugins/node/opentelemetry-instrumentation-pino/src/instrumentation.ts#L52)
    - this is currently missing tests for ESM, so implementing a workaround would require implementing tests for it first, #1942 

**Regardless of the option chosen above, we then need to:**
  - [x] bump the `import-in-the-middle` version in core, remove `import-in-the-middle` form the ignore list in `renovate.json`
  - [x] wait for a core release (done by a maintainer)
  - [ ] update core packages ~~and release a new contrib version~~ (done by a maintainer)
    - no new version needed as this was just a patch release
  - [ ] enable testing of previously unsupported Node.js in the workflows of this repo
