### ISSUE TITLE
Update usage of semantic conventions to new exported strings

### ISSUE THREAD

**Issue by JamieDanielson** [open-telemetry/opentelemetry-js-contrib#2025]
This is somewhat related to #1778 , which is for documenting current semantic convention versions for each instrumentation package.

This issue is intended to track the necessary change of updating each package to use the new exports for semantic conventions that were added in https://github.com/open-telemetry/opentelemetry-js/pull/4298 and now available in [v1.22.0](https://github.com/open-telemetry/opentelemetry-js/releases/tag/v1.22.0).

Each package will need to

- update the dependency for `@opentelemetry/semantic-conventions` to `"^1.22.0"`
- update the imported semantic convention to match the new version, i.e. `HTTP_ROUTE` becomes `SEMATTRS_HTTP_ROUTE`

Please limit PRs to a single package in order to make them quickly and easily reviewable.
If you are working on one of the below packages, please comment so others know the issue is being worked on.

- [x] `@opentelemetry/instrumentation-amqplib` #2086 
- [x] `@opentelemetry/instrumentation-cucumber` #2143
- [x] ~`@opentelemetry/instrumentation-dataloader`~
- [x] `@opentelemetry/instrumentation-fs` #2141 
- [x] `@opentelemetry/instrumentation-lru-memoizer` #2182
- [x] `@opentelemetry/instrumentation-mongoose` #2103 
- [x] `@opentelemetry/instrumentation-socket.io` #2147 
- [x] `@opentelemetry/instrumentation-tedious` #2144
- [x] `@opentelemetry/instrumentation-aws-lambda` #2181 
- [x] `@opentelemetry/instrumentation-aws-sdk` #2142 
- [x] `@opentelemetry/instrumentation-bunyan` #2195 
- [x] `@opentelemetry/instrumentation-cassandra-driver` #2139 
- [x] `@opentelemetry/instrumentation-connect` #2154
- [x] `@opentelemetry/instrumentation-dns` #2182
- [x] `@opentelemetry/instrumentation-express` #2031 
- [x] `@opentelemetry/instrumentation-fastify` #2078 
- [x] `@opentelemetry/instrumentation-generic-pool` #2182
- [x] `@opentelemetry/instrumentation-graphql` #2156 
- [x] `@opentelemetry/instrumentation-hapi` #2190 
- [x] `@opentelemetry/instrumentation-ioredis` #2191 
- [x] `@opentelemetry/instrumentation-knex` #2109 
- [x] `@opentelemetry/instrumentation-koa` #2033 
- [x] `@opentelemetry/instrumentation-memcached` #2192 
- [x] `@opentelemetry/instrumentation-mongodb` #2088 
- [x] `@opentelemetry/instrumentation-mysql` #2112 
- [x] `@opentelemetry/instrumentation-mysql2` #2115 
- [x] `@opentelemetry/instrumentation-nestjs-core` #2193 
- [x] `@opentelemetry/instrumentation-net` #2194 
- [x] `@opentelemetry/instrumentation-pg` #2053 
- [x] `@opentelemetry/instrumentation-pino` #2182
- [x] `@opentelemetry/instrumentation-redis-4` #2100 
- [x] `@opentelemetry/instrumentation-redis` #2075
- [x] `@opentelemetry/instrumentation-restify` #2098 
- [x] `@opentelemetry/instrumentation-router` #2099 
- [x] `@opentelemetry/instrumentation-winston` #2182
- [x] `@opentelemetry/instrumentation-document-load` #2039 
- [x] ~`@opentelemetry/instrumentation-long-task`~
- [x] ~`@opentelemetry/instrumentation-user-interaction`~
- [x] ~`@opentelemetry/instrumentation-undici`~ as a new instrumentation, this has a different semantic convention package

**EDIT**: updated to add other packages that will need replacements for the deprecated attributes:
- [x] ~@opentelemetry/browser-extension-autoinjection~ (skipping because this package is archived)
- [x] @opentelemetry/resource-detector-alibaba-cloud #2046 
- [x] @opentelemetry/resource-detector-aws #2047 
- [x] @opentelemetry/resource-detector-azure #2048 
- [x] @opentelemetry/resource-detector-container #2049 
- [x] @opentelemetry/resource-detector-gcp #2050 
- [x] @opentelemetry/resource-detector-instana #2051 
- [x] examples/connect #2120 
- [x] examples/express #2121 
- [x] ~examples/fastify~
- [x] examples/graphql #2122 
- [x] examples/web #2129 
- [x] @opentelemetry/sampler-aws-xray #2182
- [x] @opentelemetry/contrib-test-utils #2080 
- [x] @opentelemetry/plugin-react-load #2182
- [x] examples/memcached #2124 
- [x] examples/mongodb #2125 
- [x] examples/mysql #2126 
- [x] examples/react-load #2127 
- [x] examples/redis #2128

**Comment by MrFabio** [comment]
I am updating the koa package https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2033

**Comment by JamieDanielson** [comment]
Updating instrumentation-document-load package https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2039

**Comment by maryliag** [comment]
also updated the instrumentation-pg plugin

**Comment by JamieDanielson** [comment]
Also! A great follow-up PR (or maybe even the same PR, depending on how big the PR is) is to add the attributes to the README as listed in this issue #1778 . As an example, check out https://github.com/open-telemetry/opentelemetry-js/pull/4587 😄

**Comment by maryliag** [comment]
I can do that for the ones I updated. I will do on a follow PRs, because I currently have a few [PRs](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2055) up updating those same README files and want to avoid the conflict. So once those are merged I will update with the missing info for this.

**Comment by maryliag** [comment]
@JamieDanielson I have PRs with the updates of the README for the packages I worked on:
#2077
#2057
#2060
#2061
#2062
#2063

And the 2 PRs still waiting review for the update itself are:
#2050
#2051

**Comment by david-luna** [comment]
@JamieDanielson 

I created on PR for `fastify` instrumentation https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2078

**Comment by david-luna** [comment]
PR for `amqplib` https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2086

**Comment by david-luna** [comment]
@JamieDanielson 2 more PRs
- https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2098 for restify
- https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2099 for router

**Comment by maryliag** [comment]
Updated the ones on the examples: (btw, the `examples/fastify` is listed on the issue but there was nothing to update, and there were a few not listed on the issue but that needed update)

#2120
#2121 
#2122 
#2123 
#2124 
#2125 
#2126 
#2127 
#2128 
#2129

**Comment by JamieDanielson** [comment]
> Updated the ones on the examples: (btw, the `examples/fastify` is listed on the issue but there was nothing to update, and there were a few not listed on the issue but that needed update)
> 
> #2120 #2121 #2122 #2123 #2124 #2125 #2126 #2127 #2128 #2129

@maryliag awesome thanks! By the way a tip I learned recently, even though it's I guess less necessary if we're linking the issue anyway... if you put this into a bullet list it will expand the title for you! 🚀

**Comment by JamieDanielson** [comment]
picking up aws-sdk

**Comment by JamieDanielson** [comment]
For a smaller list, these are remaining packages that still need to get updated in this repo:

- [ ] `@opentelemetry/instrumentation-bunyan` (dev dep)
- [ ] `@opentelemetry/instrumentation-hapi`
- [ ] `@opentelemetry/instrumentation-ioredis`
- [ ] `@opentelemetry/instrumentation-memcached`
- [ ] `@opentelemetry/instrumentation-nestjs-core`
- [ ] `@opentelemetry/instrumentation-net`
- [ ] `@opentelemetry/instrumentation-long-task`
- [ ] `@opentelemetry/instrumentation-user-interaction`
- [ ] `@opentelemetry/browser-extension-autoinjection` (this is archived, do we still need to update it?)

**Comment by JamieDanielson** [comment]
These packages do not seem to have semantic conventions; I am opening a PR for them to document as such and remove any unused semantic-convention packages

- `@opentelemetry/instrumentation-lru-memoizer`
- `@opentelemetry/instrumentation-dns`
- `@opentelemetry/instrumentation-generic-pool`
- `@opentelemetry/instrumentation-pino`
- `@opentelemetry/instrumentation-winston`
- `@opentelemetry/plugin-react-load`
- `@opentelemetry/sampler-aws-xray`

**Comment by maryliag** [comment]
Updated the ones from your latest list:
- #2190 
- #2191 
- #2192 
- #2193 
- #2194 
- #2195


I didn't update `long-task` and `user-interaction` because I didn't actually see any usage of the semantic convention package on then, maybe am I missing something?
Also, don't think we should update an archived package, so I didn't do the `extension-autoinjection`

Seems to be some errors with the tests on the `hapi` one, I will try to look into it when I get some time

**Comment by trentm** [comment]
Remaining hits:

```
% rg SemanticAttributes -g '!instrumentation-undici' -w
plugins/node/opentelemetry-instrumentation-hapi/src/utils.ts
18:import { SemanticAttributes } from '@opentelemetry/semantic-conventions';
80:        [SemanticAttributes.HTTP_ROUTE]: route.path,
81:        [SemanticAttributes.HTTP_METHOD]: route.method,
90:      [SemanticAttributes.HTTP_ROUTE]: route.path,
91:      [SemanticAttributes.HTTP_METHOD]: route.method,

plugins/node/instrumentation-socket.io/test/utils.ts
20:import { SemanticAttributes } from '@opentelemetry/semantic-conventions';
60:    s => s.attributes[SemanticAttributes.MESSAGING_SYSTEM] === 'socket.io'

plugins/node/opentelemetry-instrumentation-mongodb/test/mongodb-v5-v6.test.ts
47:import { SemanticAttributes } from '@opentelemetry/semantic-conventions';
340:              mongoSpan!.attributes[SemanticAttributes.DB_STATEMENT] as string
386:                mongoSpan!.attributes[SemanticAttributes.DB_STATEMENT] as string

plugins/node/opentelemetry-instrumentation-mongodb/test/mongodb-v4.test.ts
38:import { SemanticAttributes } from '@opentelemetry/semantic-conventions';
337:              mongoSpan!.attributes[SemanticAttributes.DB_STATEMENT] as string
383:                mongoSpan!.attributes[SemanticAttributes.DB_STATEMENT] as string

plugins/node/opentelemetry-instrumentation-mongodb/test/mongodb-v3.test.ts
36:import { SemanticAttributes } from '@opentelemetry/semantic-conventions';
298:              mongoSpan!.attributes[SemanticAttributes.DB_STATEMENT] as string
344:                mongoSpan!.attributes[SemanticAttributes.DB_STATEMENT] as string
583:                mongoSpan.attributes[SemanticAttributes.NET_PEER_NAME],
587:                mongoSpan.attributes[SemanticAttributes.NET_PEER_PORT],

plugins/node/opentelemetry-instrumentation-mongodb/test/utils.ts
18:import { SemanticAttributes } from '@opentelemetry/semantic-conventions';
96:    mongoSpan.attributes[SemanticAttributes.DB_OPERATION],
100:    mongoSpan.attributes[SemanticAttributes.DB_SYSTEM],
104:    mongoSpan.attributes[SemanticAttributes.NET_PEER_NAME],
110:      mongoSpan.attributes[SemanticAttributes.DB_CONNECTION_STRING],
117:      mongoSpan.attributes[SemanticAttributes.DB_STATEMENT] as string
```

So looks like instr-mongodb and instr-socket.io missed a couple usages in tests. And then the instr-hapi PR to complete

**Comment by trentm** [comment]
> Remaining hits:

I've opened https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2210#pullrequestreview-2059204804 for the last remaining uses.

**Comment by trentm** [comment]
I believe this is done now.
