### ISSUE TITLE
[internal] improve local testing experience

### ISSUE THREAD

**Issue by pichlermarc** [open-telemetry/opentelemetry-js-contrib#2038]
A lot of the tests in this repository require some dependencies to run (postgres, mysql, redis). 

By default, we skip a lot of tests since these dependencies need to be spun up manually. Usually, to run them locally an env var needs to be set that prevents these tests from being skipped. Unfortunately this is currently inconsistent across packages.

**The goal of this issue is to streamline the testing setup and ensure scripts behave the same in each package, and add missing scripts if necessary:**
- `test:docker:start`
  - spins up one or more docker containers which are used for testing, mapping ports if necessary
- `test:docker:stop`
  - stops the containers started by `test:docker:start`
- `test:local` 
  - sets the necessary environment variables for the test
  - runs the tests

To keep review scope manageable, only work on one PR per package:

- [ ] [`@opentelemetry/instrumentation-memcached`](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-memcached/package.json)
- [ ] [`@opentelemetry/instrumentation-cassandra`](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-cassandra/package.json)
- [ ] [`@opentelemetry/instrumentation-mongodb`](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-mongodb/package.json)
- [ ] [`@opentelemetry/instrumentation-mongoose`](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/instrumentation-mongoose/package.json)
- [ ] [`@opentelemetry/instrumentation-mysql`](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-mysql/package.json)
- [ ] [`@opentelemetry/instrumentation-mysql2`](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-mysql2/package.json)
- [ ] [`@opentelemetry/instrumentation-tedious`](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/instrumentation-tedious/package.json)
- [ ] [`@opentelemetry/instrumentation-pg`](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/instrumentation-pg/package.json)
- [x] [`@opentelemetry/instrumentation-redis`](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-redis/package.json)
- [x] [`@opentelemetry/instrumentation-redis-4`](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-redis-4/package.json)
- [ ] [`@opentelemetry/instrumentation-amqplib`](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/instrumentation-amqplib/package.json)

**Additional task (documentation):**

Once all packages have been updated:

- [ ] document how to run local tests for a package in `CONTRIBUTING.md`. Since all scripts behave the same, it should be enough to mention the order of scripts to run.

**Additional resources**
- [workflow which sets the environment variables for all tests](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/146edfa89bef0b1405d573c7373af10d90639c2a/.github/workflows/unit-test.yml#L87-L115)

**Comment by pikalovArtemN** [comment]
Can i pick it ?

**Comment by pikalovArtemN** [comment]
And what do you think about [TestContainers](https://node.testcontainers.org/quickstart/) ?

**Comment by pichlermarc** [comment]
> @pikalovArtemN

thanks for volunteering. :tada: 

> And what do you think about [Testсontainers](https://node.testcontainers.org/quickstart/) ?

I've never used them directly so I'd have a few questions first:

- do they work in GitHub Workflows?
  -  from experience it's cumbersome to spin up containers in CI, and if we add it to the test code directly I'd like to go for a unified approach (able to run both in CI and locally using testcontainers, alinging local and CI testing as closely as possible)
- Can image version updates be automated using `renovate` or similar?
  - Workflow files get automatically updated by renovate if needed, so when going for a unified approach it'd also be good if we could keep this
- How does this affect Windows/macOS users that may not use Docker Desktop but an alternative such as Podman or Colima? Can they still run it? Is there more (or less) extra configuration required for them compared to the approach outlined above? :thinking:

**Comment by trentm** [comment]
Hi. I have a proposal for this at https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2214

@pikalovArtemN I hope I didn't stomp on something you were working on already.

**Comment by pichlermarc** [comment]
This is essentially done. Thank you @david-luna for getting that over the finish line in #2886 🙂
